import { useState } from "react";

import { Icon } from "@/components/ui/icon";
import { MetricStrip, PanelHeader, StatusBadge } from "@/components/ui/page-parts";
import { downloadCsv } from "@/lib/client-export";
import { campaignMetrics, initials, money, number, rate, shortDate, time } from "@/lib/presentation";
import type { DashboardData, LeadRecord, MetaEventRecord } from "@/lib/types";

type CommonProps = { data: DashboardData; onNotify: (message: string) => void };

const initialInsights = [
  { id: "response", tone: "high", title: "Demora no atendimento está reduzindo sua conversão", diagnosis: "Leads atendidos em até 10 minutos converteram 2,4 vezes mais do que os atendidos depois de uma hora.", evidence: "43 leads analisados · últimos 30 dias", impact: "R$ 12.800 / mês", action: "Criar alerta após 5 minutos e redistribuir após 15 minutos." },
  { id: "budget", tone: "medium", title: "Solar Prime pode receber mais orçamento", diagnosis: "A campanha de vídeo mantém custo por qualificado abaixo da média e ROAS acima do restante da conta.", evidence: "Campanha Captação Solar · 118 leads · 11 vendas", impact: "R$ 18.400 / mês", action: "Aumentar orçamento em 15% e acompanhar o CPL por 72 horas." },
  { id: "waste", tone: "medium", title: "Vista Parque gera volume, mas pouca receita", diagnosis: "A campanha concentra 15,6% das conversas da conta e somente uma venda atribuída.", evidence: "76 conversas · 11 qualificados · 1 venda", impact: "R$ 2.980 em mídia", action: "Revisar promessa do anúncio e público antes de ampliar a verba." },
];

export function AiInsightsPage({ onNotify }: CommonProps) {
  const [statuses, setStatuses] = useState<Record<string, string>>({});
  return <div className="stack-page"><section className="insight-summary"><div><span><Icon name="sparkles" /></span><div><small>Resumo executivo</small><h2>Há uma oportunidade clara no tempo de resposta.</h2><p>A operação mantém bom retorno, mas perde oportunidades quando o primeiro atendimento demora mais de uma hora. As recomendações abaixo usam dados do período e informam as evidências.</p></div></div><dl><div><dt>Oportunidades</dt><dd>2</dd></div><div><dt>Riscos</dt><dd>1</dd></div><div><dt>Impacto estimado</dt><dd>R$ 34.180/mês</dd></div></dl></section><section className="insights-list">{initialInsights.map((insight) => <article className="surface-panel insight-card" key={insight.id}><header><span className={insight.tone}><Icon name={insight.tone === "high" ? "warning" : "sparkles"} /></span><div><StatusBadge tone={insight.tone === "high" ? "danger" : "warning"}>{insight.tone === "high" ? "Alta prioridade" : "Oportunidade"}</StatusBadge><h2>{insight.title}</h2></div><StatusBadge tone={statuses[insight.id] ? "success" : "neutral"}>{statuses[insight.id] || "Nova"}</StatusBadge></header><div className="insight-content"><div><small>Diagnóstico</small><p>{insight.diagnosis}</p></div><div><small>Evidências utilizadas</small><p>{insight.evidence}</p></div><div><small>Ação recomendada</small><p>{insight.action}</p></div><div className="impact-box"><small>Impacto estimado</small><strong>{insight.impact}</strong><span>Confiança: alta</span></div></div><footer><button className="secondary-button" type="button" onClick={() => onNotify("Lista de leads afetados aberta.")}>Ver dados afetados</button><button className="secondary-button" type="button" onClick={() => setStatuses((current) => ({ ...current, [insight.id]: "Ignorada" }))}>Ignorar</button><button className="primary-button" type="button" onClick={() => { setStatuses((current) => ({ ...current, [insight.id]: "Em andamento" })); onNotify("Recomendação adicionada ao plano de ação."); }}>Aplicar recomendação</button></footer></article>)}</section><section className="surface-panel ai-questions"><PanelHeader title="Pergunte sobre seus dados" description="A resposta usa somente métricas disponíveis nesta organização." /><div>{["Qual campanha gerou mais receita?", "Onde estou perdendo leads?", "O que devo pausar?", "Qual vendedor converte melhor?"].map((question) => <button key={question} type="button" onClick={() => onNotify(`Pergunta preparada: ${question}`)}>{question}<Icon name="arrow" /></button>)}</div></section></div>;
}

function AttributionTimeline({ lead }: { lead: LeadRecord }) {
  const created = new Date(lead.created_at);
  const at = (minutes: number) => new Date(created.getTime() + minutes * 60_000).toLocaleTimeString("pt-BR", { hour: "2-digit", minute: "2-digit" });
  const items = [
    { time: at(-2), title: "Clique no anúncio", detail: lead.source_headline || "Anúncio não identificado", icon: "M" },
    { time: at(0), title: "Primeira mensagem no WhatsApp", detail: lead.latest_message || "Mensagem recebida", icon: "W" },
    { time: at(7), title: "Atendente respondeu", detail: "Primeiro atendimento em 7 minutos", icon: "C" },
    { time: at(18), title: "Lead classificado", detail: `Score ${lead.score}/100 · ${lead.intent}`, icon: "Q" },
    ...(lead.status === "qualified" || lead.status === "won" ? [{ time: at(20), title: "Evento enviado para a Meta", detail: "LeadSubmitted com atribuição CTWA", icon: "↗" }] : []),
  ];
  return <div className="attribution-timeline">{items.map((item) => <div key={item.title}><span>{item.icon}</span><time>{item.time}</time><div><strong>{item.title}</strong><p>{item.detail}</p></div></div>)}</div>;
}

export function AttributionPage({ data }: CommonProps) {
  const [selectedId, setSelectedId] = useState(data.leads[0]?.id || "");
  const selected = data.leads.find((lead) => lead.id === selectedId) || data.leads[0];
  if (!selected) return null;
  return <div className="attribution-layout"><section className="surface-panel data-page"><div className="page-toolbar"><select><option>Primeiro toque</option><option>Último toque</option><option>Linear</option></select><select><option>Todas as origens</option></select><div className="toolbar-spacer"/><StatusBadge tone="info">92,4% rastreados</StatusBadge></div><div className="table-wrap"><table className="data-table attribution-table"><thead><tr><th>Lead</th><th>Origem</th><th>Campanha / anúncio</th><th>Primeiro toque</th><th>Etapa</th><th>Valor atribuído</th></tr></thead><tbody>{data.leads.map((lead) => <tr key={lead.id} className={lead.id === selected.id ? "selected" : ""} onClick={() => setSelectedId(lead.id)}><td><div className="person-cell"><span>{initials(lead.display_name)}</span><div><strong>{lead.display_name}</strong><small>+{lead.wa_id}</small></div></div></td><td><span className="channel-pill">{lead.ctwa_clid ? "Meta Ads" : "Sem origem"}</span></td><td>{lead.source_headline || "Não identificado"}</td><td>{shortDate(lead.created_at)} {time(lead.created_at)}</td><td>{lead.status === "qualified" ? "Qualificado" : "Em atendimento"}</td><td>{lead.status === "won" ? "R$ 3.500" : "—"}</td></tr>)}</tbody></table></div></section><aside className="surface-panel journey-panel"><header><small>Jornada do lead</small><h2>{selected.display_name}</h2><p>{selected.client_name} · Score {selected.score}</p></header><AttributionTimeline lead={selected}/><section><h3>Modelo de atribuição</h3><dl><div><dt>Primeiro toque</dt><dd>Meta Ads</dd></div><div><dt>Último toque</dt><dd>WhatsApp</dd></div><div><dt>Origem declarada</dt><dd>Não informada</dd></div><div><dt>Origem rastreada</dt><dd>{selected.ctwa_clid ? "Confirmada por CTWA" : "Não identificada"}</dd></div></dl></section></aside></div>;
}

const reports = [
  { name: "Executivo", description: "Investimento, leads, vendas, receita e principais alertas.", updated: "Hoje, 08:00" },
  { name: "Campanhas", description: "Desempenho por campanha, conjunto e anúncio.", updated: "Ontem, 18:30" },
  { name: "Comercial", description: "Atendimento, qualificação, vendas e equipe.", updated: "Hoje, 07:45" },
  { name: "Atribuição", description: "Origens, jornadas e vendas sem identificação.", updated: "09/07/2026" },
  { name: "Perdas", description: "Gargalos, leads perdidos e follow-ups atrasados.", updated: "08/07/2026" },
  { name: "Funil", description: "Conversão e tempo médio por etapa.", updated: "Hoje, 08:15" },
];

export function ReportsPage({ data, onNotify }: CommonProps) {
  return <div className="stack-page"><section className="report-gallery">{reports.map((report) => <article className="surface-panel report-tile" key={report.name}><span><Icon name="report" /></span><div><h3>{report.name}</h3><p>{report.description}</p><small>Atualizado: {report.updated}</small></div><button className="row-action" type="button" aria-label={`Abrir relatório ${report.name}`} onClick={() => onNotify(`Relatório ${report.name} aberto.`)}>›</button></article>)}<button className="new-report-tile" type="button" onClick={() => onNotify("O criador de relatórios personalizados ainda está em desenvolvimento.")}><Icon name="plus" /><strong>Criar relatório</strong><span>Escolha métricas, período e empresa.</span></button></section><section className="surface-panel data-page"><div className="page-toolbar"><strong>Visão rápida de campanhas</strong><div className="toolbar-spacer"/><button className="secondary-button" type="button" disabled={!data.campaigns.length} onClick={() => { downloadCsv("pulsecamp-relatorio-campanhas.csv", [["Campanha", "Anúncio", "Investimento", "Leads", "Qualificados", "Vendas", "Receita", "CPL", "ROAS"], ...data.campaigns.map((campaign) => { const metric = campaignMetrics(campaign); return [campaign.campaign_name, campaign.ad_name, campaign.spend, campaign.conversations, campaign.qualified, campaign.sales, campaign.revenue, metric.cpl, metric.roas]; })]); onNotify("CSV exportado."); }}><Icon name="download" />CSV</button><button className="secondary-button" type="button" onClick={() => onNotify("Exportação PDF ainda está em desenvolvimento.")}>PDF</button><button className="primary-button" type="button" onClick={() => onNotify("Agendamento depende da integração de e-mail, ainda não configurada.")}>Agendar envio</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Campanha</th><th>Investimento</th><th>Leads</th><th>Qualificados</th><th>Vendas</th><th>Receita</th><th>CPL</th><th>ROAS</th></tr></thead><tbody>{data.campaigns.map((campaign) => { const metric = campaignMetrics(campaign); return <tr key={campaign.id}><td><strong>{campaign.campaign_name}</strong><small>{campaign.ad_name}</small></td><td>{money(campaign.spend)}</td><td>{campaign.conversations}</td><td>{campaign.qualified}</td><td>{campaign.sales}</td><td><strong>{money(campaign.revenue)}</strong></td><td>{money(metric.cpl, 2)}</td><td>{metric.roas.toFixed(2)}x</td></tr>; })}</tbody></table></div></section></div>;
}

function eventStatus(event: MetaEventRecord) {
  return { pending: "Processando", dry_run: "Validado em teste", sent: "Enviado", failed: "Falhou", skipped: "Sem atribuição" }[event.status];
}

export function EventsPage({ data, onNotify, onRetry }: CommonProps & { onRetry: (eventId: string) => void }) {
  return <div className="stack-page"><MetricStrip items={[{ label: "Processados", value: String(data.events.filter((event) => event.status === "sent" || event.status === "dry_run").length), detail: "Recebidos pela integração" }, { label: "Aguardando", value: String(data.events.filter((event) => event.status === "pending").length), detail: "Na fila de envio" }, { label: "Com falha", value: String(data.events.filter((event) => event.status === "failed").length), detail: "Podem ser reenviados" }, { label: "Modo CAPI", value: data.runtime.capiDryRun ? "Teste" : "Produção", detail: `Graph API ${data.runtime.graphVersion}` }]} /><section className="surface-panel data-page"><div className="page-toolbar"><select><option>Todos os status</option></select><select><option>LeadSubmitted</option></select><div className="toolbar-spacer"/><button className="secondary-button" type="button" onClick={() => onNotify("Documentação do evento aberta.")}>Ver documentação</button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Lead</th><th>Empresa</th><th>Evento</th><th>Score</th><th>Identificador</th><th>Tentativas</th><th>Criado em</th><th>Status</th><th>Ação</th></tr></thead><tbody>{data.events.map((event) => <tr key={event.id}><td><strong>{event.lead_name}</strong></td><td>{event.client_name}</td><td><code>{event.event_name}</code></td><td>{event.score}</td><td><code className="truncate-code">{event.event_id}</code></td><td>{event.attempts}</td><td>{shortDate(event.created_at)} {time(event.created_at)}</td><td><StatusBadge tone={event.status === "sent" || event.status === "dry_run" ? "success" : event.status === "failed" ? "danger" : event.status === "skipped" ? "warning" : "info"}>{eventStatus(event)}</StatusBadge></td><td>{event.status === "failed" || event.status === "skipped" ? <button className="text-action" type="button" onClick={() => onRetry(event.id)}>Reenviar</button> : "—"}</td></tr>)}</tbody></table></div></section></div>;
}

export function GoalsPage({ data, onNotify }: CommonProps) {
  const goals = [
    { name: "Receita mensal", current: data.totals.revenue, target: 1_250_000, unit: "currency", owner: "Operação", due: "31/07/2026" },
    { name: "Vendas atribuídas", current: data.totals.sales, target: 42, unit: "number", owner: "Comercial", due: "31/07/2026" },
    { name: "Leads qualificados", current: data.totals.qualified, target: 180, unit: "number", owner: "Marketing", due: "31/07/2026" },
    { name: "Tempo de resposta", current: 7, target: 5, unit: "minutes", owner: "Atendimento", due: "15/07/2026" },
  ];
  return <div className="stack-page"><section className="surface-panel data-page"><div className="page-toolbar"><strong>Metas do período</strong><div className="toolbar-spacer"/><button className="primary-button" type="button" onClick={() => onNotify("Formulário de nova meta aberto.")}><Icon name="plus" />Criar meta</button></div><div className="goals-grid">{goals.map((goal) => { const progress = goal.unit === "minutes" ? Math.min(goal.target / goal.current, 1) : Math.min(goal.current / goal.target, 1); const display = (value: number) => goal.unit === "currency" ? money(value) : goal.unit === "minutes" ? `${value} min` : number(value); return <article key={goal.name}><header><span><Icon name="goal" /></span><StatusBadge tone={progress >= .9 ? "success" : progress >= .7 ? "info" : "warning"}>{rate(progress)}</StatusBadge></header><h3>{goal.name}</h3><div className="goal-values"><strong>{display(goal.current)}</strong><span>de {display(goal.target)}</span></div><div className="progress-bar"><i style={{ width: `${progress * 100}%` }} /></div><footer><span>Responsável: {goal.owner}</span><span>Até {goal.due}</span></footer></article>; })}</div></section></div>;
}
